x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__WEBSERVER__SECRET_KEY: milestone3secret
    MLFLOW_TRACKING_URI: sqlite:////opt/airflow/mlflow.db
    MLFLOW_EXPERIMENT_NAME: milestone3-airflow
    MLFLOW_MODEL_NAME: milestone3-iris-model
    PYTHONPATH: /opt/airflow
  volumes:
    - ./:/opt/airflow
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  mlflow:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "mlflow ui --backend-store-uri sqlite:////opt/airflow/mlflow.db --host 0.0.0.0 --port 5000"
    ports:
      - "5001:5000"


volumes:
  postgres-db-volume:
